# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Screen.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QProgressBar, QPushButton, QSizePolicy, QWidget)
import recursos_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1200, 799)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.framePrincipal = QFrame(Dialog)
        self.framePrincipal.setObjectName(u"framePrincipal")
        self.framePrincipal.setGeometry(QRect(0, 0, 1200, 800))
        self.framePrincipal.setFrameShape(QFrame.Shape.StyledPanel)
        self.framePrincipal.setFrameShadow(QFrame.Shadow.Raised)
        self.label_5 = QLabel(self.framePrincipal)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(440, 50, 331, 31))
        palette = QPalette()
        brush = QBrush(QColor(0, 102, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush1)
        brush2 = QBrush(QColor(127, 127, 127, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush2)
        brush3 = QBrush(QColor(170, 170, 170, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush3)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        brush4 = QBrush(QColor(0, 0, 0, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush4)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush1)
        brush5 = QBrush(QColor(255, 255, 220, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush4)
        brush6 = QBrush(QColor(0, 102, 255, 128))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush6)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush1)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush6)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush1)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush6)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush1)
#endif
        self.label_5.setPalette(palette)
        font = QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_5.setStyleSheet(u"color: #0066FF;\n"
"font-size: 30px;        /* tamanho */")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.painel5 = QLabel(self.framePrincipal)
        self.painel5.setObjectName(u"painel5")
        self.painel5.setEnabled(True)
        self.painel5.setGeometry(QRect(910, 190, 201, 208))
        self.painel5.setStyleSheet(u"")
        self.painel5.setPixmap(QPixmap(u":/imagens/imagens/SKILL5.png"))
        self.painel5.setScaledContents(True)
        self.label = QLabel(self.framePrincipal)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 1200, 800))
        self.label.setPixmap(QPixmap(u":/imagens/imagens/logo.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.python = QProgressBar(self.framePrincipal)
        self.python.setObjectName(u"python")
        self.python.setGeometry(QRect(230, 635, 118, 23))
        font1 = QFont()
        font1.setFamilies([u"Cascadia Code"])
        font1.setPointSize(14)
        font1.setBold(False)
        self.python.setFont(font1)
        self.python.setTabletTracking(False)
        self.python.setStyleSheet(u"QProgressBar::chunk { background-color: #FFF099; }")
        self.python.setValue(24)
        self.python.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.python.setTextVisible(True)
        self.python.setInvertedAppearance(False)
        self.painel9 = QLabel(self.framePrincipal)
        self.painel9.setObjectName(u"painel9")
        self.painel9.setEnabled(True)
        self.painel9.setGeometry(QRect(810, 465, 201, 208))
        self.painel9.setStyleSheet(u"")
        self.painel9.setPixmap(QPixmap(u":/imagens/imagens/SKILL8.png"))
        self.painel9.setScaledContents(True)
        self.label_2 = QLabel(self.framePrincipal)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 50, 341, 31))
        palette1 = QPalette()
        brush7 = QBrush(QColor(255, 80, 45, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush7)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush2)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush3)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush7)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush7)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush4)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush5)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush4)
        brush8 = QBrush(QColor(255, 80, 45, 128))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush1)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush7)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush7)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush7)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush4)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush1)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush7)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush2)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush3)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush7)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush7)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush4)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush5)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush8)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush1)
#endif
        self.label_2.setPalette(palette1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: #FF502D;\n"
"font-size: 24px;        /* tamanho */\n"
"font-weight: bold;      /* negrito */")
        self.powerbi = QProgressBar(self.framePrincipal)
        self.powerbi.setObjectName(u"powerbi")
        self.powerbi.setGeometry(QRect(340, 360, 118, 23))
        self.powerbi.setFont(font1)
        self.powerbi.setTabletTracking(False)
        self.powerbi.setAutoFillBackground(False)
        self.powerbi.setStyleSheet(u"QProgressBar::chunk { background-color: #FFF099; }")
        self.powerbi.setValue(70)
        self.powerbi.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.powerbi.setTextVisible(True)
        self.powerbi.setInvertedAppearance(False)
        self.painel1 = QLabel(self.framePrincipal)
        self.painel1.setObjectName(u"painel1")
        self.painel1.setEnabled(True)
        self.painel1.setGeometry(QRect(85, 190, 201, 208))
        self.painel1.setStyleSheet(u"")
        self.painel1.setPixmap(QPixmap(u":/imagens/imagens/SKILL1.png"))
        self.painel1.setScaledContents(True)
        self.painel1.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.process = QProgressBar(self.framePrincipal)
        self.process.setObjectName(u"process")
        self.process.setGeometry(QRect(850, 635, 118, 23))
        self.process.setFont(font1)
        self.process.setTabletTracking(False)
        self.process.setStyleSheet(u"QProgressBar::chunk { background-color: #FF9999; }\n"
"")
        self.process.setValue(24)
        self.process.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.process.setTextVisible(True)
        self.process.setInvertedAppearance(False)
        self.painel6 = QLabel(self.framePrincipal)
        self.painel6.setObjectName(u"painel6")
        self.painel6.setEnabled(True)
        self.painel6.setGeometry(QRect(190, 465, 201, 208))
        self.painel6.setStyleSheet(u"")
        self.painel6.setPixmap(QPixmap(u":/imagens/imagens/SKILL6.png"))
        self.painel6.setScaledContents(True)
        self.painel7 = QLabel(self.framePrincipal)
        self.painel7.setObjectName(u"painel7")
        self.painel7.setEnabled(True)
        self.painel7.setGeometry(QRect(400, 465, 201, 208))
        self.painel7.setStyleSheet(u"")
        self.painel7.setPixmap(QPixmap(u":/imagens/imagens/SKILL7.png"))
        self.painel7.setScaledContents(True)
        self.java = QProgressBar(self.framePrincipal)
        self.java.setObjectName(u"java")
        self.java.setGeometry(QRect(950, 360, 118, 23))
        self.java.setFont(font1)
        self.java.setTabletTracking(False)
        self.java.setStyleSheet(u"QProgressBar::chunk { background-color: #FF9999; }\n"
"")
        self.java.setValue(24)
        self.java.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.java.setTextVisible(True)
        self.java.setInvertedAppearance(False)
        self.painel8 = QLabel(self.framePrincipal)
        self.painel8.setObjectName(u"painel8")
        self.painel8.setEnabled(True)
        self.painel8.setGeometry(QRect(610, 465, 201, 208))
        self.painel8.setStyleSheet(u"")
        self.painel8.setPixmap(QPixmap(u":/imagens/imagens/SKILL9.png"))
        self.painel8.setScaledContents(True)
        self.painel3 = QLabel(self.framePrincipal)
        self.painel3.setObjectName(u"painel3")
        self.painel3.setEnabled(True)
        self.painel3.setGeometry(QRect(510, 190, 201, 208))
        self.painel3.setStyleSheet(u"")
        self.painel3.setPixmap(QPixmap(u":/imagens/imagens/SKILL3.png"))
        self.painel3.setScaledContents(True)
        self.vba = QProgressBar(self.framePrincipal)
        self.vba.setObjectName(u"vba")
        self.vba.setGeometry(QRect(550, 360, 118, 23))
        self.vba.setFont(font1)
        self.vba.setTabletTracking(False)
        self.vba.setStyleSheet(u"QProgressBar::chunk { background-color: #B699FF; }")
        self.vba.setValue(24)
        self.vba.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.vba.setTextVisible(True)
        self.vba.setInvertedAppearance(False)
        self.painel4 = QLabel(self.framePrincipal)
        self.painel4.setObjectName(u"painel4")
        self.painel4.setEnabled(True)
        self.painel4.setGeometry(QRect(710, 190, 201, 208))
        self.painel4.setStyleSheet(u"")
        self.painel4.setPixmap(QPixmap(u":/imagens/imagens/SKILL4.png"))
        self.painel4.setScaledContents(True)
        self.redes = QProgressBar(self.framePrincipal)
        self.redes.setObjectName(u"redes")
        self.redes.setGeometry(QRect(650, 635, 118, 23))
        self.redes.setFont(font1)
        self.redes.setTabletTracking(False)
        self.redes.setStyleSheet(u"QProgressBar::chunk { background-color: #99CAFF; }\\n")
        self.redes.setValue(24)
        self.redes.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.redes.setTextVisible(True)
        self.redes.setInvertedAppearance(False)
        self.label_3 = QLabel(self.framePrincipal)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 90, 211, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush2)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush3)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush4)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush5)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush4)
        brush9 = QBrush(QColor(255, 255, 255, 128))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush1)
#endif
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush3)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush4)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush5)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush1)
#endif
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush3)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush4)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush5)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush1)
#endif
        self.label_3.setPalette(palette2)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: #FFFFFF;\n"
"font-size: 24px;        /* tamanho */")
        self.sql = QProgressBar(self.framePrincipal)
        self.sql.setObjectName(u"sql")
        self.sql.setGeometry(QRect(750, 360, 118, 23))
        self.sql.setFont(font1)
        self.sql.setTabletTracking(False)
        self.sql.setStyleSheet(u"QProgressBar::chunk { background-color: #99CAFF; }\\n")
        self.sql.setValue(24)
        self.sql.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sql.setTextVisible(True)
        self.sql.setInvertedAppearance(False)
        self.painel2 = QLabel(self.framePrincipal)
        self.painel2.setObjectName(u"painel2")
        self.painel2.setEnabled(True)
        self.painel2.setGeometry(QRect(300, 190, 201, 208))
        self.painel2.setStyleSheet(u"")
        self.painel2.setPixmap(QPixmap(u":/imagens/imagens/SKILL2.png"))
        self.painel2.setScaledContents(True)
        self.ia = QProgressBar(self.framePrincipal)
        self.ia.setObjectName(u"ia")
        self.ia.setGeometry(QRect(440, 635, 118, 23))
        self.ia.setFont(font1)
        self.ia.setTabletTracking(False)
        self.ia.setStyleSheet(u"QProgressBar::chunk { background-color: #B699FF; }")
        self.ia.setValue(24)
        self.ia.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ia.setTextVisible(True)
        self.ia.setInvertedAppearance(False)
        self.btnpowerbi = QPushButton(self.framePrincipal)
        self.btnpowerbi.setObjectName(u"btnpowerbi")
        self.btnpowerbi.setGeometry(QRect(330, 190, 141, 208))
        self.btnpowerbi.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 239, 0, 30); /* leve destaque */\n"
"}")
        self.btnia = QPushButton(self.framePrincipal)
        self.btnia.setObjectName(u"btnia")
        self.btnia.setGeometry(QRect(430, 465, 141, 208))
        self.btnia.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(128, 0, 255, 30); /* leve destaque */\n"
"}")
        self.btnexcel = QPushButton(self.framePrincipal)
        self.btnexcel.setObjectName(u"btnexcel")
        self.btnexcel.setGeometry(QRect(113, 190, 141, 208))
        self.btnexcel.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 255, 0, 20); /* leve destaque */\n"
"}")
        self.btnjava = QPushButton(self.framePrincipal)
        self.btnjava.setObjectName(u"btnjava")
        self.btnjava.setGeometry(QRect(940, 190, 141, 208))
        self.btnjava.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 5, 30); /* leve destaque */\n"
"}")
        self.btnsql = QPushButton(self.framePrincipal)
        self.btnsql.setObjectName(u"btnsql")
        self.btnsql.setGeometry(QRect(740, 190, 141, 208))
        self.btnsql.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 187, 255, 30); /* leve destaque */\n"
"}")
        self.btnprocess = QPushButton(self.framePrincipal)
        self.btnprocess.setObjectName(u"btnprocess")
        self.btnprocess.setGeometry(QRect(840, 465, 141, 208))
        self.btnprocess.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 5, 30); /* leve destaque */\n"
"}")
        self.btnredes = QPushButton(self.framePrincipal)
        self.btnredes.setObjectName(u"btnredes")
        self.btnredes.setGeometry(QRect(640, 465, 141, 208))
        self.btnredes.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 187, 255, 30); /* leve destaque */\n"
"}")
        self.btnpython = QPushButton(self.framePrincipal)
        self.btnpython.setObjectName(u"btnpython")
        self.btnpython.setGeometry(QRect(220, 465, 141, 208))
        self.btnpython.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 217, 0, 30); /* leve destaque */\n"
"}\n"
"")
        self.btnvba = QPushButton(self.framePrincipal)
        self.btnvba.setObjectName(u"btnvba")
        self.btnvba.setGeometry(QRect(540, 190, 141, 208))
        self.btnvba.setStyleSheet(u"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(128, 0, 255, 30); /* leve destaque */\n"
"}")
        self.excel = QProgressBar(self.framePrincipal)
        self.excel.setObjectName(u"excel")
        self.excel.setGeometry(QRect(125, 360, 118, 23))
        self.excel.setFont(font1)
        self.excel.setTabletTracking(False)
        self.excel.setStyleSheet(u"QProgressBar::chunk { background-color: #99FF99; }")
        self.excel.setValue(24)
        self.excel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.excel.setTextVisible(True)
        self.excel.setInvertedAppearance(False)
        self.label.raise_()
        self.label_5.raise_()
        self.painel9.raise_()
        self.label_2.raise_()
        self.painel1.raise_()
        self.painel6.raise_()
        self.painel7.raise_()
        self.painel8.raise_()
        self.painel3.raise_()
        self.painel4.raise_()
        self.label_3.raise_()
        self.painel2.raise_()
        self.painel5.raise_()
        self.java.raise_()
        self.excel.raise_()
        self.powerbi.raise_()
        self.ia.raise_()
        self.vba.raise_()
        self.sql.raise_()
        self.process.raise_()
        self.redes.raise_()
        self.python.raise_()
        self.btnpython.raise_()
        self.btnia.raise_()
        self.btnredes.raise_()
        self.btnprocess.raise_()
        self.btnexcel.raise_()
        self.btnsql.raise_()
        self.btnvba.raise_()
        self.btnjava.raise_()
        self.btnpowerbi.raise_()

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Minhas Skills", None))
#if QT_CONFIG(accessibility)
        self.painel5.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel5.setText("")
        self.label.setText("")
#if QT_CONFIG(accessibility)
        self.painel9.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel9.setText("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"VITOR TAMARINDO CORREA", None))
#if QT_CONFIG(statustip)
        self.painel1.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(accessibility)
        self.painel1.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel1.setText("")
#if QT_CONFIG(accessibility)
        self.painel6.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel6.setText("")
#if QT_CONFIG(accessibility)
        self.painel7.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel7.setText("")
#if QT_CONFIG(accessibility)
        self.painel8.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel8.setText("")
#if QT_CONFIG(accessibility)
        self.painel3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel3.setText("")
#if QT_CONFIG(accessibility)
        self.painel4.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel4.setText("")
        self.label_3.setText(QCoreApplication.translate("Dialog", u"DESENVOLVEDOR", None))
#if QT_CONFIG(accessibility)
        self.painel2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.painel2.setText("")
        self.btnpowerbi.setText("")
        self.btnia.setText("")
        self.btnexcel.setText("")
        self.btnjava.setText("")
        self.btnsql.setText("")
        self.btnprocess.setText("")
        self.btnredes.setText("")
        self.btnpython.setText("")
        self.btnvba.setText("")
    # retranslateUi

